### ISSUE TITLE
can you provide some configure/setup tips?

### ISSUE THREAD

**Issue by caochao** [SardineFish/zogra-renderer#1]
Hi @SardineFish , thanks for your efforts. This repository is very interesting so I plan to study the code to learn webgl.
but, I am not familiar with the web, and the README seems to lack the steps to configure npm dependencies and webpack. Can you provide some tips for building/running steps in the README?

**Comment by SardineFish** [comment]
Sorry for relying late. This project is still in developing and some design of my code are complicate for learning webgl. I recommen learning by https://webglfundamentals.org/ and https://webgl2fundamentals.org/. 
And I'm planning to add building instructions in next release version.
